### ISSUE TITLE
New Characters Pack (Reisen, Eirin, Nitori, Marisa)

### ISSUE THREAD

**Issue by SmugilouGazilou** [SmugilouGazilou/touhouemblem#9]
# New Characters Being Added!
-------------------------------------------------
My plans are to get Reisen, Nitori, and Eirin along with Marisa all worked in and functioning to some degree in the new release. As such, **new specialized** features will come with them which will be **explained here** and possibly in other areas. Be wary. 

(I'll add checkmarks as the features are added in as per usual.)
--------------------------------------------------
# Reisen, Fancy Illusions and other Delusions
--------------------------------------------------
 My plans for Reisen limit very few right now.  I've already got a select amount of features planned to come in with her.  Although most are a bit iffy. Ya know? I'll likely make her into a support-based character more so than anything.  Here's a bit more on what'll be added to her.  **This is not limited to just character-based things but features added to the game due to their addition as well.** 

She'll be pretty... Odd at first. I'll work that out and hopefully get some input on what to do with her.
I'm also not sure what to make her weapon. So. This is also a thing. Maybe pistols since in the PS4 Version of ULiL and in LoLK, she used one. (Kinda?)

------------------------------------------------------
# Reisen Additions
- [x] **New damage type:** Illusion! Basically a new damage type and with it, enemies are weak to certain types of damage, yadayada.

- [ ] **Character Splitting:** This is essentially like a slime splitting off into two. Take your stats and split into another form. It's basically summons that are based off the active users' stats and can vary in multiple ways.

- [x] **New Status Effect: Confusion!** This is exactly what it seems like. Confuse the enemy, make them do random stuff, and same goes for allies. It's not hard to understand.

--------------------------------------------------------

# Eirin, Drugs, and Chemical Processes

--------------------------------------------------------

Eirin is pretty much planned out near to fully planned out. She's going to be a dancer-type unit (see: #6) with the unique ability of crafting in-battle as well as using item skills (see: #5 ) in order to better aid and buff the team. She'll be near to pure support with some optional DPS involved.  Since the game will run on the Attribute System until further notice, one could try to mix in some DPS.  

As expected. She'll be using a Bow as her main weapon type.
As such. Here's what's coming with her inevitably.
------------------------------------------
# Eirin Additions

- [ ] **New Ability Type: Synthesis** This pretty much will be one of the main staples of Eirin. As stated above. She'll be able to craft mid-battle and by utilizing the currently being worked on Individual Inventories (see: #8 ) , she'll be a vital unit to protect and carry in battle as for her support will be very valued. Especially with being able to kill units and loot the battlefields for ingredients to brew up a tonic or something.

- [ ] **Dancer-Typed Units and Skills!** If you don't want to go read #6 here. Basically these units and skills will be able to allow enemies and party members extra actions in a phase.

- [ ] **Item Skills!** If you're too lazy to read #5 here, short and simple version is. Skills are expected to consume items.

-------------------------------------------------

# Nitori, Gadgets, Guns, And Nuclear Apocalypses.

-------------------------------------------------

Nitori is also pretty much planned out. She'll be able to deploy Mechanations to serve as other roles in her place, which might make her a good Solo Character. She'll also be able to boost and upgrade characters in-battle amongst other things.

She'll pretty much be a Summoner-Ranged DPS Hybrid Character.

She'll be able to use an assortment of guns and ammo as her main weapons not limited to but including: Handguns, Rocket Launchers, Submachine Guns, Snipers, and Shotguns.

---------------------------------------------------

# Nitori Additions

- [ ] **Ammo For Weapons!** This in itself will be an extensive topic. So I'll make that at another date. But the short gist is, weapons like guns and such won't be usable without ammo now. 

- [ ] **Individual Items!** This one is simple. Two potions are separate entities. Same applies for weapons and armor. This'll allow greater coverage over stuff.

- [ ] **Item Charges!** This is relatively simple. Since items are individual, some items will have charges available so that you can have different instances of the same item with different amounts of uses.
I had plans to give Nitori the ability to use such items to give other party members special "Mechanation" based skills or temporary weapons such as Air Drones and such.

- [ ] **Specialized Enchants/Weapon Attachments!** Nitori will have guns. These guns will have 100 round drum mags that specifically shoot out darts on the 92nd and 34th bullet and have over five iron sights on it and have a thermal scope as well as a laser sight, a heavy barrel, a silenced rocket launcher, a folding stock and many other things.  ** And that's just one gun.**

- [ ] **Turrets, Medibots, And Other Mechs!** Nitori will be the tinker-type of the group. She'll effectively be the more ranged DPS orientation of Eirin with a dash of Summoner within. She'll be able to fill in for those who need to rest or cooldown with her extensive line of various robots and such. Need covering fire while you run away?

Toss out a drone.

Need to get quick heals on the field without wasting time? Medibot, coming right up.

Need some support on the front lines? One Stationary Turret will do the trick!

So on, so on. 

-------------------------------------------

# Marisa, Lack Of Brooms, And The Precious Thing

-------------------------------------------

Marisa is going to be an odd one. She'll basically be a melee-ranged magic spellcaster hybrid, pretty much essentially relying on MP and TP Consumption and Meter Management.

There's not much she'll be providing into the game but she'll have a lot of magic up her sleeves. Oh. And Stealing stuff too. So she'll be able to use  the enemies' own wits against them.

-------------------------------------------

# Marisa Additions

- [ ] **Item Stealing!** "See that book in Patchouli's Hand? _That's also my book._" Marisa will be able to steal items off of enemies as well as from special areas on the battle maps.

- [ ] **Skill Stealing!** That's right. She'll be able to mimic and either (varying on skill), be able to temporarily or permanently learn a skill. Although it'll always be a weaker version of the original until Marisa trains it up.

---------------------------------------------

That's all I've got planned for them as of now. If you'd like to, feel free to give your input on this here and there for now.
